apiVersion: apps/v1
kind: Deployment
metadata:
  name: service01
  namespace: kong
  labels:
    app: service01
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service01
  template:
    metadata:
      labels:
        app: service01
    spec:
      containers:
        - name: service01
          image: 192.168.56.2:32000/service01
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          command: ["flask", "run","--host","0.0.0.0"]
---
apiVersion: v1
kind: Service
metadata:
  name: service01
  namespace: kong
  labels:
    app: service01
    namespace: kong
spec:
  type: NodePort
  selector:
    app: service01
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30036
      protocol: TCP