apiVersion: apps/v1
kind: Deployment
metadata:
  name: service02
  namespace: kong
  labels:
    app: service02
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service02
  template:
    metadata:
      labels:
        app: service02
    spec:
      containers:
        - name: service02
          image: 192.168.56.2:32000/service02
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          command: ["flask", "run","--host","0.0.0.0"]
---
apiVersion: v1
kind: Service
metadata:
  name: service02
  namespace: kong
  labels:
    app: service02
    namespace: kong
spec:
  type: NodePort
  selector:
    app: service02
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30037
      protocol: TCP